Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -935,12 +935,14 @@ exit 0' >$RCLOCAL
 		}
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m◉" || var_sks1="\033[1;31m○"
     	[[ $(screen -list | grep -wc 'websecurity') != '0' ]] && var_sks3="\033[1;32m◉" || var_sks3="\033[1;31m○"
+		[[ $(screen -list | grep -wc 'proxydt') != '0' ]] && var_sks4="\033[1;32m◉" || var_sks4="\033[1;31m○"
 		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m◉" || var_sks2="\033[1;31m○"
 		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m◉" || sksop="\033[1;31m○"
 		echo ""
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSOCKS SSH $var_sks1 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $var_sks2 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET SECURITY $var_sks3 \033[0m"
+		echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mPROXY DTUNNEL MOD $var_sks4 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mSOCKS OPENVPN $sksop \033[0m"
 		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
 		echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS SOCKS SSH\033[0m"
@@ -1117,8 +1119,67 @@ elif [[ "$resposta" = '3' ]]; then
         
         fun_socks
     fi
+
+
+elif [[ "$resposta" = '4' ]]; then
+    clear
+    if ps x | grep -w proxydt | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo -e "\E[41;1;37m             PROXY DTUNNEL               \E[0m"
+        echo ""
+        fun_proxydtoff() {
+            for pidproxy in $(screen -ls | grep ".proxydt" | awk {'print $1'}); do
+                screen -r -S "$pidproxy" -X quit
+            done
+            [[ $(grep -wc "proxydt" /etc/autostart) != '0' ]] && {
+                sed -i '/proxydt/d' /etc/autostart
+            }
+            sleep 1
+            screen -wipe >/dev/null
+        }
+        echo -e "\033[1;32mDESATIVANDO O PROXY DTUNNEL\033[1;33m"
+        echo ""
+        fun_bar 'fun_proxydtoff'
+        echo ""
+        echo -e "\033[1;32mPROXY DTUNNEL DESATIVADO COM SUCESSO!\033[1;33m"
+        
+        fun_socks
+    else
+        echo -e "\E[44;1;37m             PROXY DTUNNEL               \E[0m"
+        echo ""
+        echo -e "\033[1;32mQUAL PORTA DESEJA ULTILIZAR ? \033"
+        echo ""
+        echo -e "\033[1;32mEXEMPLO :\033[1;33m80 ou 8080\033"
+        echo ""
+        read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m: ")" porta
+        [[ -z "$porta" ]] && {
+            echo ""
+            echo -e "\033[1;31mPorta invalida!"
+            
+            fun_socks
+        }
+        verif_ptrs $porta
+        fun_iniproxydt() {
+            sleep 1
+            screen -dmS proxydt /etc/SSHPlus/proxydt --port $porta --http --openvpn-port --response PROXYDT
+            [[ $(grep -wc "proxydt" /etc/autostart) = '0' ]] && {
+                echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxydt' -X quit;  screen -dmS proxydt /etc/SSHPlus/proxydt --port $porta --http --openvpn-port --response PROXY; }" >>/etc/autostart
+            } || {
+                sed -i '/proxydt/d' /etc/autostart
+                echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxydt' -X quit;  screen -dmS proxydt /etc/SSHPlus/proxydt --port $porta --http --openvpn-port --response PROXY; }" >>/etc/autostart
+            }
+        }
+        echo ""
+        echo -e "\033[1;32mINICIANDO O PROXY DTUNNEL\033[1;33m"
+        echo ""
+        fun_bar 'fun_iniproxydt'
+        echo ""
+        echo -e "\033[1;32PROXY DTUNNEL ATIVADO COM SUCESSO\033[1;33m"
+        
+        fun_socks
+    fi
+
     
-		elif [[ "$resposta" = '4' ]]; then
+		elif [[ "$resposta" = '5' ]]; then
 			if ps x | grep -w open.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				echo -e "\E[41;1;37m            SOCKS OPENVPN             \E[0m"
@@ -1178,7 +1239,7 @@ elif [[ "$resposta" = '3' ]]; then
 				sleep 3
 				fun_socks
 			fi
-		elif [[ "$resposta" = '5' ]]; then
+		elif [[ "$resposta" = '6' ]]; then
 			if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				sockspt=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
 				clear
@@ -1215,7 +1276,7 @@ elif [[ "$resposta" = '3' ]]; then
 				sleep 2
 				fun_socks
 			fi
-		elif [[ "$resposta" = '6' ]]; then
+		elif [[ "$resposta" = '7' ]]; then
 			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				msgsocks=$(cat /etc/SSHPlus/proxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
@@ -1310,7 +1371,7 @@ elif [[ "$resposta" = '3' ]]; then
 				sleep 2
 				fun_socks
 			fi
-        		elif [[ "$resposta" = '7' ]]; then
+        		elif [[ "$resposta" = '8' ]]; then
 			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				msgsocks=$(cat /etc/SSHPlus/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
@@ -1583,6 +1644,12 @@ echo -e "\033[0;31m║\033[0m"
 			} || {
 				sts3="\033[1;31m○ "
 			}
+                        [[ "$(netstat -tlpn | grep 'proxydt' | wc -l)" != '0' ]] && {
+				echo -e "\033[01;31m║\033[1;32mSERVICO: \033[1;33mPROXY DTUNNEL \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'proxydt' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts4="\033[1;32m◉ "
+			} || {
+				sts4="\033[1;31m○ "
+			}
 			[[ "$(netstat -tlpn | grep 'proxy' | wc -l)" != '0' ]] && {
 				echo -e "\033[01;31m║\033[1;32mSERVICO: \033[1;33mRUSTYPROXY \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'proxy' | awk -F ":" {'print $4'} | xargs)"
 				sts0="\033[1;32m◉ "
@@ -1609,7 +1676,7 @@ echo -e "\033[0;31m║\033[0m"
 			echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 05 •\033[1;34m]\033[1;37m ➩  \033[1;33mSSLH MULTIPLEX \033[01;31m $sts7\033[0m"
 			echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 06 •\033[1;34m]\033[1;37m ➩  \033[1;33mWEBSOCKET - Corretor \033[01;31m $sts3\033[0m"
 			echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 07 •\033[1;34m]\033[1;37m ➩  \033[1;33mMENU APACHE  \033[0m"
-			echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 08 •\033[1;34m]\033[1;37m ➩  \033[1;33mMENU RUSTYPROXY  \033[0m"
+			echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 08 •\033[1;34m]\033[1;37m ➩  \033[1;33mMENU RUSTYPROXY $sts0\033[0m"
 			echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 			echo -e "\033[01;31m\033[0m"
 			echo -e "\033[0;36m░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░\033[0m"
